# This file is part of the YesWiki Extension zfuture43.
# Authors : see README.md file that was distributed with this source code.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
parameters:
  favorites_activated: false
  # for edit config action
  zfuture43_editable_config_params:
    - favorites_activated

services:
  _defaults:
    autowire: true
    public: true

  YesWiki\Zfuture43\Service\:
    resource: 'services/*'

  YesWiki\Zfuture43\Controller\:
    resource: 'controllers/*'

  YesWiki\Zfuture43\Service\FormManager:
    decorates: YesWiki\Bazar\Service\FormManager